### ISSUE TITLE
Custom sms not working 

### ISSUE THREAD

**Issue by tejaspatil-29** [samay825/Sms-Bomb#44]
Traceback (most recent call last): File "/data/data/com.termux/files/home/Sms-Bomb/main.py", line 25, in main.Xyz() File "main.py", line 979, in main.Xyz File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "main.py", line 718, in goibi File "main.py", line 719, in main.MainFunctions.goibi File "main.py", line 720, in main.MainFunctions.goibi File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1192, in json return loads(stripped.decode(encoding)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 340, in decode raise JSONDecodeError("Extra data", s, end) json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

**Comment by ermkmandawar** [comment]
![Screenshot_2024-07-16-06-15-19-71_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/7614f8cf-5c46-48d6-bbc0-14c0f609e8ee)

**Comment by samay825** [comment]
updated please check it out
